name: Проверка расписания

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Записать время запуска
        run: |
          echo "Автоматический запуск работает"
          date -u
